apiVersion: v1
kind: Service
metadata:
  name: igp-service
  labels:
    app: igp-devops-project
spec:
  selector:
    app: igp-devops-project
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005